apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: toidibangiay-prod
data:
  FRONTEND_URL: "https://toidibangiay.vn"
  CART_SERVICE_URL: "http://cart-service:3003/api"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3007/api"
  PAYMENT_SERVICE_URL: "http://payment-service:3006/api"
  PAYOS_CANCEL_URL: "https://toidibangiay.vn/checkout/cancel"
  ORDER_SERVICE_URL: "http://order-service:3004/api"
  AUTH_SERVICE_URL: "http://auth-service:3002/api"
  PAYOS_API_URL: "https://api-merchant.payos.vn"
  NODE_ENV: "production"
  VNPAY_URL: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  PORT: "4000"
  PAYOS_RETURN_URL: "https://toidibangiay.vn/checkout/success"
  PRODUCT_SERVICE_URL: "http://product-service:4001"
  INVENTORY_SERVICE_URL: "http://inventory-service:3005/api"