apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 061083040425.dkr.ecr.us-east-2.amazonaws.com/gateway
    newTag: 80ac8d179ac32f7448dfdafefd51b84f2c6c369d