apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 061083040425.dkr.ecr.us-east-2.amazonaws.com/gateway
    newTag: 08bba47d461ff1498ddaf84bb7064c8ba2493016