apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: toidibangiay-prod
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3006"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: payment-service
          image: PLACEHOLDER_IMAGE
          ports:
            - containerPort: 3006
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30