apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: toidibangiay-prod
spec:
  selector:
    app: payment-service
  ports:
    - port: 3006
      targetPort: 3006
  type: ClusterIP