apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: toidibangiay-prod
data:
  USER_SERVICE_URL: "http://user-service:3001"
  NODE_ENV: "production"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3007"
  PAYMENT_SERVICE_URL: "http://payment-service:3006"
  CART_SERVICE_URL: "http://cart-service:3003"
  PRODUCT_SERVICE_URL: "http://product-service:4001"
  PORT: "3004"
  INVENTORY_SERVICE_URL: "http://inventory-service:3005"