apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - apps/gateway
  - apps/auth-service
  - apps/user-service
  - apps/product-service
  - apps/cart-service
  - apps/order-service
  - apps/inventory-service
  - apps/payment-service
  - apps/notification-service
  - apps/search-service
  - cloudflared
  - ingress/ingress.yaml
