apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 061083040425.dkr.ecr.us-east-2.amazonaws.com/auth-service
    newTag: 3f2bdffae47665eab2dff0082239f88eaacd9abb