apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 061083040425.dkr.ecr.us-east-2.amazonaws.com/search-service
    newTag: 7cc66384718a125bf3600d181a3a6522d893759f