apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: toidibangiay-prod
data:
  PORT: "3001"
  NODE_ENV: "production"
  COOKIE_SECURE: "true"
  COOKIE_SAME_SITE: "none"
  FRONTEND_URL: "https://toidibangiay.shop"
  REFRESH_TOKEN_TTL_DAYS: "30"
  JWT_ACCESS_TTL_SECONDS: "900"