apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: toidibangiay-prod
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: product-service
          image: PLACEHOLDER_IMAGE
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30