apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 061083040425.dkr.ecr.us-east-2.amazonaws.com/product-service
    newTag: 52b48e39e6be7196448dd212155da7bad69730b8