apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: toidibangiay-prod
data:
  PORT: "3007"
  SMTP_PORT: "587"
  NODE_ENV: "production"
  SMTP_SECURE: "false"
  SMTP_FROM: "Tôi Đi Bán Giày <no-reply@toidibangiay.vn>"
  SMTP_HOST: "smtp.gmail.com"